### ISSUE TITLE
Very Sleepy doesn't profile C++ dll loaded by a .NET exe.

### ISSUE THREAD

**Issue by urspraneeth** [VerySleepy/verysleepy#29] opened 2016-05-19 10:29 UTC
Thank you for this simple yet very powerful tool. It helps a lot. 

Ok now, What I mean is that the profiling information doesn't show the function names and modules of my C++ dlls when they are launched by a .NET exe. Very Sleepy could locate the pdbs too. 

Do we have any support or recommendations for this scenario?

**Comment by CyberShadow** [comment] 2016-05-19 18:18
That is strange.

So you have tried to profile a DLL with a native .EXE, and you see symbol names, but the very same DLL with a .NET EXE fails to resolve symbols?

**Comment by urspraneeth** [comment] 2016-05-20 10:24
Yes, you are right! 

Does Sleepy have any limitations with how the process launching dlls is kicked off? I mean any should process have any privileges or rights? 

I also receive this exception when I profile a 64 bit application. How do I resolve and help sleepy complete profiling successfully?

![sleepy exception](https://cloud.githubusercontent.com/assets/19423706/15424951/0187f528-1ea3-11e6-92a1-e11d3d000eae.JPG)

**Comment by CyberShadow** [comment] 2016-05-20 10:37
Which version are you using?

**Comment by urspraneeth** [comment] 2016-05-23 02:55
64 bit version 0.90.

**Comment by CyberShadow** [comment] 2016-05-23 04:19
Could you try [this slightly newer test build](dump.thecybershadow.net/4c2886915a8d6f55b30b2ac53627d366/verysleepy-0.91-test-2015-04-24.exe)?

**Comment by urspraneeth** [comment] 2016-05-23 05:55
Sure..Will try and let you know how it goes. Thanks!

**Comment by urspraneeth** [comment] 2016-05-24 11:18
I'm sorry I'm still having the same problem of the exception.

**Comment by urspraneeth** [comment] 2016-05-26 16:48
I'm trying to sleepy logs. Can you please answer my queries below? Thanks in advance.

1. How can we know how many times a function is called using info in Very Sleepy?
2. What do you mean by "Samples"?
3. Are the call stacks displayed comprehensive? Does all the call stacks in which my function is hit are logged? Can I count the no of call stacks to be the no of times my function is called?

Please provide me any document or sample which can help me understand all info that is presented by VS.

**Comment by CyberShadow** [comment] 2016-05-26 18:04
> How can we know how many times a function is called using info in Very Sleepy?

Very Sleepy is not an instrumenting profiler, it is a polling one. It cannot provide the exact number a function was called, only a statistical average of how often a function is called compared to other functions.

> What do you mean by "Samples"?

Sampling profilers, such as Very Sleepy, work by periodically pausing the program, inspecting its state, then resuming. Information gained from such an inspection is called a sample. This has advantages and disadvantages.

> Are the call stacks displayed comprehensive? 

The more often a call stack is executed, the more likely it is to appear in the call stack list.

> Does all the call stacks in which my function is hit are logged? 

There is no guarantee that all executed call stacks will be logged.

> Can I count the no of call stacks to be the no of times my function is called?

No, it is simply the number of samples that the program was observed to have that stack trace.

**Comment by CyberShadow** [comment] 2016-05-26 18:04
There is some more information on Wikipedia:

https://en.wikipedia.org/wiki/Profiling_(computer_programming)#Data_granularity_in_profiler_types

**Comment by urspraneeth** [comment] 2016-05-31 03:35
Thank you for the information. It really helps.

**Comment by CyberShadow** [comment] 2017-02-02 13:23
> I also receive below exception after sometime of profiling a 64 or 32 bit native application. How do I resolve this and help sleepy complete profiling successfully? It doesn't matter whether I profile multiple or single thread.

I think I found the cause for that error. Hopefully it should be resolved by 5d84b3767942902e6b72ca659ca2398c39699f25.

Can you try [the latest version](https://ci.appveyor.com/api/projects/CyberShadow/verysleepy/artifacts/setup.exe?branch=master) and see if the problem exists there?

**Comment by CyberShadow** [comment] 2021-08-19 10:41
> Can you try [the latest version](https://ci.appveyor.com/api/projects/CyberShadow/verysleepy/artifacts/setup.exe?branch=master) and see if the problem exists there?

There is now a release:
https://github.com/VerySleepy/verysleepy/releases

I'm guessing that this problem is no longer relevant to you, but in case it is, please do leave a comment or open a new issue. Thanks!

**Closed by CyberShadow** 2021-08-19 10:41 UTC
Labels: bug
