### ISSUE TITLE
Invalid full path handling

### ISSUE THREAD

**Issue by wingrime** [VerySleepy/verysleepy#11] opened 2014-12-31 14:12 UTC
An example in Source window:
[ Could not open file 'G:\m_proj/G:/QT/Tools/mingw482_32/i686-w64-mingw32/include/c++/bits/shared_ptr_base.h'. ]
Looks like full path not handled right way

**Comment by CyberShadow** [comment] 2015-01-16 19:29
Sorry for the late reply, I must have lost the notification email.

I might be wrong, but I'm not seeing any path concatenation in the source code, so I think this path is generated by the debug engine.

Could you tell me how to reproduce this issue?

Or, can you post a saved `.sleepy` profile result, or check if the path is like that in its `Symbols.txt` file? (`.sleepy` files are ZIP files with a renamed extension.)

**Comment by wingrime** [comment] 2015-02-01 09:16
Yep, Symbols.txt looks like:
0x40277b "main" "display" "G:\\m_proj/G:/m_proj/main.cpp" 66
0x402782 "main" "display" "G:\\m_proj/G:/m_proj/main.cpp" 67

**Comment by CyberShadow** [comment] 2015-02-01 09:39
Yes, that string is taken directly from the debug engine.

What compiler did you use to build the program?

**Comment by wingrime** [comment] 2015-02-04 07:56
Mingw gcc 4.3
1 февр. 2015 г. 14:39 пользователь "Vladimir Panteleev" <
notifications@github.com> написал:

**Comment by CyberShadow** [comment] 2015-02-17 14:39
Can you give this version a try?
http://dump.thecybershadow.net/58c4691eb50f22da99ad2adbce0a2644/verysleepy-0.91-test-2015-02-17.exe

**Comment by CyberShadow** [comment] 2015-02-26 02:59
Ping?

**Comment by wingrime** [comment] 2015-02-26 04:55
Soon .. Wait a couple of days...
26 февр. 2015 г. 7:59 пользователь "Vladimir Panteleev" <
notifications@github.com> написал:

**Comment by CyberShadow** [comment] 2015-02-26 14:03
OK, then please try this version instead:
http://dump.thecybershadow.net/98079a7c593fd4142330f634c22903ab/verysleepy-0.91-test-2015-02-26.exe

**Comment by CyberShadow** [comment] 2015-03-03 20:11
Could you please give the above version a try?

It uses a new MinGW debug information parser.

I would like to release a new version of Very Sleepy, but it needs testing, so I would appreciate if you could see how well it works in your case.

**Comment by wingrime** [comment] 2015-03-31 15:11
Very sorry for patience, but looks likes this build broken. I don't see any symbols at all. 0.90 works, but path sometimes invalid

**Comment by CyberShadow** [comment] 2015-03-31 17:25
As we found out, the new Dr. MinGW symbol engine currently has the limitation that it can't read symbols after the process exited, so you will need to stop profiling before the program exits. That, or, in Very Sleepy options, change the MinGW symbol engine back to Wine DbgHelp.

**Comment by CyberShadow** [comment] 2015-04-29 02:10
@wingrime [Here's a new build](http://dump.thecybershadow.net/4c2886915a8d6f55b30b2ac53627d366/verysleepy-0.91-test-2015-04-24.exe) which doesn't have the above-described problem, can you try it?

**Comment by MAP94** [comment] 2016-10-06 04:33
I tested this build (the last one you linked) and it works for me. thx

**Comment by CyberShadow** [comment] 2017-01-21 02:17
As there has been no feedback from the issue submitter for over a year, and per the comment above, closing. 

Please file a new issue for MinGW bugs that are still present in the build linked to from my comment above.

**Closed** 2017-02-01 12:25 UTC
Labels: bug, mingw
