### ISSUE TITLE
Can`t change "Symbol search path" 

### ISSUE THREAD

**Issue by CodeImp** [VerySleepy/verysleepy#31] opened 2016-06-27 10:39 UTC
First time this option work normally, but after restart program impossible to change path, add new or move up/down.
I found "SymbolSearchPath" parameter in registry and clear him. After I can add new paths, but only first time.

**Comment by CyberShadow** [comment] 2017-01-14 19:53
Apologies for the late reply. I haven't been able to reproduce this issue, so I believe this issue might be fixed in master. If you can build Very Sleepy from source, you could check if the problem still occurs.

**Comment by Fixer-007** [comment] 2017-02-19 17:45
I can reproduce this on build I downloaded on appveyour today.

**Comment by guirlo** [comment] 2017-04-05 20:32
I just ran into this issue. Thanks for the "SymbolSearchPath" parameter in registry trick, that saved me!

**Comment by AlanIWBFT** [comment] 2019-04-24 05:32
Looks like the problem happens when there are very long paths which cause the list box to over extend. `src\wxProfilerGUI\optionsdlg.cpp: 93` needs some modification. Changing `wxSize(-1, 75)` to `wxSize(0, 75)` can prevent it from extending excessively and occluding the buttons. Btw I would also suggest adding `wxLB_HSCROLL` to view long paths better.

**Comment by CyberShadow** [comment] 2019-04-25 02:00
I'm assuming this was fixed by #65, please comment if this is still a problem.

**Closed by CyberShadow** 2019-04-25 02:00 UTC
Labels: bug
